# This file is used for creation and execution of nginex Docker container
FROM nginx

# Command to be execute at the time of container creation
# COPY content of 'static_html_directory' to the path '/usr/share/nginx/html' inside docker
COPY static_html_directory /usr/share/nginx/html
